---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/podinfo
  - ../../storage/base
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: cobrowse
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
        spec:
          minReplicas: 3
      target:
        name: podinfo
        kind: HorizontalPodAutoscaler
    - patch: |-
        - op: remove
          path: "/spec/template/spec/volumes"
      target:
        name: podinfo
        kind: Deployment
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: podinfo
        spec:
          template:
            spec:
              volumes:
                - name: data
                  ephemeral:
                    volumeClaimTemplate:
                      metadata:
                        labels:
                          type: pd-standard
                      spec:
                        accessModes: [ "ReadWriteOnce" ]
                        storageClassName: "pd-standard"
                        resources:
                          requests:
                            storage: 1Gi