---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cobrowse-pv-0
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: pd-standard
  volumeMode: Filesystem
  gcePersistentDisk:
    pdName: podinfo-disk-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cobrowse-pv-1
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: pd-standard
  volumeMode: Filesystem
  gcePersistentDisk:
    pdName: podinfo-disk-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cobrowse-pv-2
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: pd-standard
  volumeMode: Filesystem
  gcePersistentDisk:
    pdName: podinfo-disk-2